# Permalinks
permalink:        '/:title.html'

# Setup
title:            "Adriaan's blog"
tagline:          "Adriaan's coding blog"
description:      'Just learnings, no bullshit'
url:              https://blog.adriaan.io
baseurl:          /
disqus_shortname: demaandvanadriaan

author:
  name:           'Adriaan van Rossum'
  url:            https://twitter.com/adriaanvrossum

paginate:         50

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "post"
      is_post: true

gems:
  - jekyll-redirect-from
