# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            "Adriaan's blog"
tagline:          "Adriaan's coding blog"
description:      'Just learnings, no bullshit'
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Adriaan van Rossum'
  url:            https://twitter.com/harianus

paginate:         5

# Custom vars
version:          0.0.1

github:
  repo:           https://github.com/poole/hyde
