# Dependencies
markdown:         redcarpet2
highlighter:      pygments

# Permalinks
permalink:        '/:title.html'
relative_permalinks: true

# Setup
title:            "Adriaan's blog"
tagline:          "Adriaan's coding blog"
description:      'Just learnings, no bullshit'
url:              https://blog.adriaan.io
baseurl:          /

author:
  name:           'Adriaan van Rossum'
  url:            https://twitter.com/harianus

paginate:         5
